{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: maas-api-db-url
  labels:
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.database.user }}:{{ .Values.database.password }}@postgres-service:5432/{{ .Values.database.name }}?sslmode=disable"
{{- end }}
