{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: postgres
    name: postgres
{{- end }}
