{{- if .Values.database.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  labels:
    app: postgres
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
{{- end }}
