apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    openshift.io/display-name: granite-3-3-8b
    serving.kserve.io/deploymentMode: RawDeployment
  name: granite-3-3-8b
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  model:
    name: granite-3-3-8b
    uri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.3-2b-instruct'
  replicas: 1
  router:
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
    route: {}
  template:
    containers:
      - image: 'registry.redhat.io/rhoai/odh-vllm-cpu-rhel9@sha256:bae57975dfe153afc799e868e6a27ec1e502f68d4337a74dc6455a6bc326d02c'
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 30
        name: main
        resources:
          limits:
            cpu: '4'
            memory: 32Gi
          requests:
            cpu: '2'
            memory: 16Gi