{{- $existingSecret := lookup "v1" "Secret" "maas-api-keys" "api-key-maas-user" }}
{{- if not $existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key-maas-user
  namespace: maas-api-keys
  labels:
    authorino.kuadrant.io/managed-by: authorino
  annotations:
    user.authorino.kuadrant.io/userid: "maas-user"
    user.authorino.kuadrant.io/groups: "tier-free-users"
    argocd.argoproj.io/sync-options: "Prune=false,Delete=false"
    argocd.argoproj.io/compare-options: "IgnoreExtraneous"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
type: Opaque
stringData:
  api_key: "{{ randAlphaNum 20 }}"
{{- end }}
